name: Unity
on: push
jobs:
  test-and-build:
    name: Test and Build (${{ matrix.unityVersion }}, ${{ matrix.platform }})
    runs-on: ubuntu-latest
    container: unityci/editor:${{ matrix.unityVersion }}-${{ matrix.platform }}
    env:
      unityCommand: /opt/unity/Editor/Unity -batchmode -nographics -logfile /dev/stdout -quit
      unityCommand-no-quit: /opt/unity/Editor/Unity -batchmode -nographics -logfile /dev/stdout
      projectPath: test-project
      buildPath: build-${{ matrix.unityVersion }}-${{ matrix.platform }}
      buildName: DefaultScene
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.1.17f1
          - 2020.2.1f1
        platform:
          - windows-mono-0
    steps:
      - name: Create test project folder
        run: mkdir -p ${{ env.projectPath }}/Packages/EntityTween
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.projectPath }}/Packages/EntityTween
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.projectPath }}/Library
          key: Library-${{ matrix.unityVersion }}-${{ matrix.platform }}
          restore-keys: |
            Library-${{ matrix.unityVersion }}-
            Library-
      - name: Activate and create project
        run: ${{ env.unityCommand }} -username "${{ secrets.UNITY_EMAIL }}" -password "${{ secrets.UNITY_PASSWORD }}" -serial "${{ secrets.UNITY_SERIAL }}" -createProject '${{ env.projectPath }}'
      - name: Unit tests
        run: ${{ env.unityCommand-no-quit }} -projectPath '${{ env.projectPath }}' -runTests -testPlatform PlayMode
      - name: Build
        run: ${{ env.unityCommand }} -projectPath '${{ env.projectPath }}' -executeMethod Timespawn.EntityTween.Editor.CI.BuildUtils.BuildDefaultScene ${{ env.buildPath }}/${{ env.buildName }} ${{ matrix.platform }}
      - name: Return license
        if: ${{ always() }}
        run: ${{ env.unityCommand }} -returnLicense
      - name: Upload unit tests results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ${{ env.projectPath }}/TestResults*.xml
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.buildPath }}
          path: ${{ env.projectPath }}/${{ env.buildPath }}
          
        
  
